cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/fonts'

brew 'ack'
brew 'ansible'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'shellcheck'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask '1password'
cask 'airmail'
cask 'alfred'
cask 'atom'
cask 'caffeine'
cask 'dockertoolbox'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'livereload'
cask 'seashore'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
cask 'vagrant-manager'
cask 'vagrant'
cask 'vmware-fusion'
cask 'virtualbox'
cask 'vlc'


# fonts
cask 'font-inconsolata'
cask 'font-source-code-pro'
